### Numpy: Package for multidimensional array

In [2]:
import numpy as np 

In [3]:
simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [20]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [21]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [22]:
np.random.rand(3,5)

array([[0.74006043, 0.92025587, 0.47715778, 0.34301408, 0.77857379],
       [0.6678171 , 0.53430886, 0.70671435, 0.29836631, 0.96870861],
       [0.79110457, 0.72128866, 0.55288275, 0.41034766, 0.04255056]])

In [24]:
rand_array=np.random.randint(0,10,50)
rand_array

array([3, 0, 3, 0, 8, 8, 2, 4, 0, 5, 3, 6, 2, 2, 3, 9, 1, 8, 1, 4, 6, 6,
       7, 7, 4, 2, 2, 4, 8, 0, 4, 8, 6, 5, 3, 5, 0, 2, 9, 7, 5, 3, 1, 0,
       7, 7, 1, 1, 5, 6])

In [28]:
arr=np.random.randn(2,4)
arr

array([[-0.55613091,  0.60001896, -1.18672493,  0.34345718],
       [-0.64743627, -0.26281494,  0.55340966,  0.49062296]])

In [29]:
np.random.randint(20,56,100)

array([20, 27, 22, 33, 20, 37, 27, 20, 36, 25, 34, 43, 21, 51, 40, 27, 35,
       48, 54, 32, 25, 28, 28, 46, 52, 54, 31, 47, 43, 53, 47, 39, 45, 23,
       33, 39, 28, 44, 44, 53, 55, 53, 21, 48, 43, 37, 50, 32, 54, 37, 47,
       31, 22, 24, 38, 23, 49, 31, 21, 38, 28, 20, 43, 31, 21, 43, 37, 30,
       55, 24, 27, 29, 42, 23, 43, 46, 26, 36, 32, 51, 46, 53, 46, 29, 38,
       33, 29, 31, 31, 24, 29, 21, 39, 25, 31, 25, 28, 45, 33, 41])

In [30]:
np.random.randint(2,100)

98

In [31]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
rand_array=np.random.randint(0,10,50)
rand_array

array([2, 2, 9, 6, 5, 9, 6, 5, 9, 2, 7, 9, 8, 4, 9, 4, 0, 2, 1, 4, 3, 2,
       0, 8, 0, 1, 8, 7, 0, 5, 0, 5, 7, 4, 6, 7, 1, 8, 9, 2, 3, 7, 8, 1,
       0, 4, 7, 8, 2, 6])

In [34]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
rand_array.max()

9

In [36]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [37]:
rand_array.argmax()

2

In [39]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
a=np.random.rand(2,3)
a

array([[0.54910928, 0.12373505, 0.38603071],
       [0.67456058, 0.61474983, 0.04397191]])

In [42]:
a.T

array([[0.54910928, 0.67456058],
       [0.12373505, 0.61474983],
       [0.38603071, 0.04397191]])

In [43]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
sample_array[0]

10

In [45]:
sample_array[2:5]

array([12, 13, 14])

In [47]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [48]:
sample_array[0:7]

array([ 10, 100, 100, 100,  14,  15,  16])

In [49]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([ 10, 100, 100, 100,  14,  15,  16])

In [50]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])